# Generated by Django 3.2.25 on 2024-05-06 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Manager', 'MNG'), ('Software', 'SWE'), ('Team Lead', 'TL')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
